### ISSUE TITLE
Error: EPERM: operation not permitted, symlink

### ISSUE THREAD

**Issue by Youdaman** [pure-css/pure-site#382]
Running `npm start` causes the following error, something to do with not being able to create a symlink?

```
$ npm start

> pure-site@1.18.13 start C:\Users\Youdaman\Desktop\pure-site-master
> node server.js

An unexpected error occurred. Watcher quitting.
Error: EPERM: operation not permitted, symlink 'C:\Users\Youdaman\Desktop\pure-site-master\tmp\broccoli_merge_trees-outp
ut_path-6UYt5Esf.tmp' -> 'C:\Users\Youdaman\Desktop\pure-site-master\build'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1068:18)
    at Watcher.<anonymous> (C:\Users\Youdaman\Desktop\pure-site-master\lib\watcher.js:41:8)
    at emitOne (events.js:101:20)
    at Watcher.emit (events.js:188:7)
    at Watcher.<anonymous> (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\broccoli\lib\watcher.js:52:14)
    at tryCatch (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\rsvp\dist\rsvp.js:2415:5)
Pure Server listening on 5000
```

I was able to hit http://localhost:5000 once but it looked like some styles were broken, and subsequent visits showed the following Express error:

```
Express
500 TypeError: Cannot convert undefined or null to object
   at graphToYUIConfig (C:\Users\Youdaman\Desktop\pure-site-master\middleware\expose-module-graph.js:35:12)
   at Object.handle (C:\Users\Youdaman\Desktop\pure-site-master\middleware\expose-module-graph.js:22:24)
   at next (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\connect\lib\proto.js:174:15)
   at run (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\express-yui\lib\middleware.js:151:21)
   at C:\Users\Youdaman\Desktop\pure-site-master\node_modules\express-yui\lib\middleware.js:148:25
   at Array.<anonymous> (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\express-yui\lib\middleware.js:100:13)
   at run (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\express-yui\lib\middleware.js:143:36)
   at C:\Users\Youdaman\Desktop\pure-site-master\node_modules\express-yui\lib\middleware.js:148:25
   at Array.<anonymous> (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\express-yui\lib\middleware.js:63:13)
   at run (C:\Users\Youdaman\Desktop\pure-site-master\node_modules\express-yui\lib\middleware.js:143:36)
```

Running on Windows 10, Node v6.10.3 and npm v3.10.10.

**Comment by redonkulus** [comment]
I do not have a windows machine so I cannot help debug. Please reopen if this is something that needs to be fixed.
